export interface HotOffer {
    "sales": number,
    "deliveryOrder": number,
    "invoice": number,
    "productList": number,
    "salesList" : SaleList[],
    "deliveryOrderList": number,
    "invoiceList": number,
    "company": number,
    "warehouse": number,
    "status": number,
    "timestamp": string,
    "message": number
}

export interface SaleList {
    "id": number,
    "salesHistory": SaleHistory[],
    "deliveryOrder":[],
    "type": string,
    "salesOfferType": string,
    "status": string,
    "employeeId": number,
    "customerId": number,
    "transportId": number,
    "sourceCompanyId": number,
    "sourceWarehouseId": number,
    "destinationCompanyId": number,
    "destinationWarehouseId": number,
    "expectedDate": string,
    "title": string,
    "remarks": string,
    "totalPrice": "",
    "grossWt": "",
    "netWt": string,
    "materialDescription": string,
    "lorryType": string,
    "coilsBundle": string,
    "lorryNumber": number,
    "productCategory": string,
    "productShape": string,
    "totalQuantity": number,
    "grossQuantity": number,
    "packaging": string,
    "regionPreffered": string,
    "location": string,
    "isTreadLeadBuy": boolean,
    "gstInvoice": string,
    "loadingUnloadingCharges": string,
    "packagingCharges": string,
    "deliveryCharges": string,
    "anyOtherCharges": string,
    "contactPersonName": string,
    "contactPersonMobile": string,
    "contactPersonWhatsapp": string,
    "contactPersonEmail": string,
    "thicknessRange": number,
    "widthRange": number,
}

export interface SaleHistory {
"salesHistoryId": number,
"salesId": number,
"createdBy": number,
"createdDate": "2019-07-29T11:51:56.000+0000",
"lastModifiedBy": number,
"lastModifiedDate": "2019-07-29T11:52:17.000+0000",
"salesType": string;
    
}